name: mealup_restaurant_side
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # For UIs
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  dotted_line: ^3.0.0
  flutter_advanced_switch: ^2.0.2+2
  fl_chart: ^0.36.1

  # For Networking
  retrofit: ^1.3.4+1

  # For Model
  json_serializable: ^4.0.2
  freezed_annotation: ^0.14.0
  json_annotation: any

  # For Utilities
  get: ^4.0.0-nullsafety.0

  # For Key-Value local storage
  shared_preferences: ^2.0.5

  #Progress
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^5.0.0

  connectivity: ^3.0.3
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  geocoder: ^0.2.1
  fluttertoast: ^8.0.7
  provider: ^4.3.1
  country_code_picker: ^2.0.1
  toggle_switch: ^1.0.0+1
  image_picker: ^0.6.5+3
  sizer: ^2.0.13
  url_launcher: ^6.0.6
  onesignal_flutter: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  retrofit_generator: ^1.4.1
  build_runner: ^1.11.5
  async: ^2.6.1


  # For Model
  freezed: ^0.14.0


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_screen.png
  color_dark: "#1a1a1a"
  image_dark: assets/images/splash_screen.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectfill

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/localization/languages/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova.ttf
    - family: ProximaBold
      fonts:
        - asset: assets/fonts/proximabold.otf
    - family: ProximaThin
      fonts:
        - asset: assets/fonts/proximathin.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
